### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by piyushK52** [drboog/ProFusion#3]
I am using A10 with 40GB VRAM but am unable to run the fine-tuning part.  getting this error

`OutOfMemoryError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 39.56 GiB total capacity; 36.60 GiB already allocated; 288.56 MiB free; 37.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

P.S. batch size of 1 worked

**Comment by drboog** [comment]
Hi, when you use a smaller batch size, be carful about the iteration number and learning rate, you may need to tune them to get good results.
